name: Deploy Streamlit App to Hugging Face Spaces (Git Push)

on:
  push:
    branches:
      - main # Assurez-vous que c'est la bonne branche

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          # Permet l'accès complet au répertoire cloné (nécessaire pour le git push)
          fetch-depth: 0 

      # Cette étape configure Git pour s'authentifier auprès de Hugging Face
      - name: Configure Git for Hugging Face Push
        run: |
          git config --global user.email "ci-cd@huggingface.co"
          git config --global user.name "GitHub Actions Deployer"
          
          # Crée l'URL distante pour votre Space en utilisant le HF_TOKEN
          HF_REPO="https://user:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/MaFae/Jedha_Bloc_5_GetAround"
          echo "::set-output name=hf_repo_url::$HF_REPO"
        id: setup

      # Cette étape pousse les fichiers vers votre Space Hugging Face
      - name: Push to Hugging Face Space
        run: |
          # Ajoute votre Space comme remote appelé 'hf'
          git remote add hf "${{ steps.setup.outputs.hf_repo_url }}"
          
          # Force le push de votre branche actuelle (main) vers la branche 'main' du Space HF
          # Cela écrase le contenu du Space HF avec le contenu de votre GitHub.
          git push hf main --force